SPGLib.c: Drop const, to fix a build failure with newer gcc
cc -Wdate-time -D_FORTIFY_SOURCE=2 -g -O2 -ffile-prefix-map=/<<PKGBUILDDIR>>=. -flto=auto -ffat-lto-objects -fstack-protector-strong -fstack-clash-protection -Wformat -Werror=format-security -fcf-protection -fdebug-prefix-map=/<<PKGBUILDDIR>>=/usr/src/cod-tools-3.7.0+dfsg-1ubuntu1 -Wall -Wno-unused-value \
	-I. -c \
	`perl -MConfig -e 'print join(" ", @Config{qw(ccflags optimize cccdlflags)}, "-I$Config{archlib}/CORE")'` \
	source.c source_wrap.c
source.c: In function ‘get_sym_dataset’:
source.c:36:27: error: assignment of read-only location ‘lattice[i][j]’
   36 |             lattice[i][j] = SvNV( (SV*)
      |                           ^
source.c:49:29: error: assignment of read-only location ‘positions[i][j]’
   49 |             positions[i][j] = SvNV( (SV*)
      |                             ^
make[2]: *** [Makelocal-SWIG-module:36: source.o] Error 1
make[2]: Leaving directory '/<<PKGBUILDDIR>>/src/lib/perl5/COD/SPGLib'
make[1]: *** [Makefile:83: /<<PKGBUILDDIR>>/src/lib/perl5/COD/SPGLib.pm] Error 2
make[1]: Leaving directory '/<<PKGBUILDDIR>>'